#pragma checksum "..\..\..\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "002D6E8CAF2260D535F8E006C1FE0E39D60F5A87"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MahApps.Metro.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace MeuApp {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : MahApps.Metro.Controls.MetroWindow, System.Windows.Markup.IComponentConnector {
        
        
        #line 94 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ChatsNavButton;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ChatsUnreadBadge;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ChatsUnreadCountText;
        
        #line default
        #line hidden
        
        
        #line 140 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SidebarUserName;
        
        #line default
        #line hidden
        
        
        #line 141 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SidebarUserRole;
        
        #line default
        #line hidden
        
        
        #line 142 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SidebarUserEmail;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock WelcomeText;
        
        #line default
        #line hidden
        
        
        #line 176 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SearchFriendsBox;
        
        #line default
        #line hidden
        
        
        #line 181 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TestFirebaseButton;
        
        #line default
        #line hidden
        
        
        #line 183 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AccountSettingsButton;
        
        #line default
        #line hidden
        
        
        #line 191 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ChatsContent;
        
        #line default
        #line hidden
        
        
        #line 199 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer TeamsContent;
        
        #line default
        #line hidden
        
        
        #line 212 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TeamEntryOptionsButton;
        
        #line default
        #line hidden
        
        
        #line 226 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup TeamEntryOptionsPopup;
        
        #line default
        #line hidden
        
        
        #line 263 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TeamsEmptyStateCard;
        
        #line default
        #line hidden
        
        
        #line 273 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TeamJoinCard;
        
        #line default
        #line hidden
        
        
        #line 279 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TeamJoinCodeTextBox;
        
        #line default
        #line hidden
        
        
        #line 301 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TeamJoinStatusText;
        
        #line default
        #line hidden
        
        
        #line 311 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TeamCreationCard;
        
        #line default
        #line hidden
        
        
        #line 340 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TeamNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 345 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox TeamCourseComboBox;
        
        #line default
        #line hidden
        
        
        #line 357 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox TeamClassComboBox;
        
        #line default
        #line hidden
        
        
        #line 362 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TeamClassIdTextBox;
        
        #line default
        #line hidden
        
        
        #line 373 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox TeamUcInput;
        
        #line default
        #line hidden
        
        
        #line 399 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel TeamUcsPanel;
        
        #line default
        #line hidden
        
        
        #line 410 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox TeamMemberInput;
        
        #line default
        #line hidden
        
        
        #line 438 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel TeamMembersPanel;
        
        #line default
        #line hidden
        
        
        #line 443 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CreateTeamButton;
        
        #line default
        #line hidden
        
        
        #line 453 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TeamCreationStatusText;
        
        #line default
        #line hidden
        
        
        #line 463 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TeamListCard;
        
        #line default
        #line hidden
        
        
        #line 467 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel TeamListPanel;
        
        #line default
        #line hidden
        
        
        #line 471 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TeamWorkspaceCard;
        
        #line default
        #line hidden
        
        
        #line 472 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContentControl TeamWorkspaceHost;
        
        #line default
        #line hidden
        
        
        #line 478 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel CalendarContent;
        
        #line default
        #line hidden
        
        
        #line 484 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel FilesContent;
        
        #line default
        #line hidden
        
        
        #line 490 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer SettingsContent;
        
        #line default
        #line hidden
        
        
        #line 509 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AccountNameText;
        
        #line default
        #line hidden
        
        
        #line 515 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox NicknameTextBox;
        
        #line default
        #line hidden
        
        
        #line 527 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ProfessionalTitleTextBox;
        
        #line default
        #line hidden
        
        
        #line 537 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ProgrammingLanguageInput;
        
        #line default
        #line hidden
        
        
        #line 563 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel ProgrammingLanguagesTagsPanel;
        
        #line default
        #line hidden
        
        
        #line 570 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BioTextBox;
        
        #line default
        #line hidden
        
        
        #line 575 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SkillsTextBox;
        
        #line default
        #line hidden
        
        
        #line 586 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PortfolioLinkTextBox;
        
        #line default
        #line hidden
        
        
        #line 591 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LinkedInLinkTextBox;
        
        #line default
        #line hidden
        
        
        #line 596 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SaveProfessionalProfileButton;
        
        #line default
        #line hidden
        
        
        #line 606 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ProfessionalProfileStatusText;
        
        #line default
        #line hidden
        
        
        #line 620 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button LogoutButton;
        
        #line default
        #line hidden
        
        
        #line 681 "..\..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChatDarkModeToggle;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/MeuApp;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.7.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ChatsNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 94 "..\..\..\MainWindow.xaml"
            this.ChatsNavButton.Click += new System.Windows.RoutedEventHandler(this.NavButton_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.ChatsUnreadBadge = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.ChatsUnreadCountText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            
            #line 121 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NavButton_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 122 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NavButton_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 123 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NavButton_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 124 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NavButton_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.SidebarUserName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.SidebarUserRole = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.SidebarUserEmail = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.WelcomeText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.SearchFriendsBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            
            #line 177 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SearchFriends_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.TestFirebaseButton = ((System.Windows.Controls.Button)(target));
            
            #line 181 "..\..\..\MainWindow.xaml"
            this.TestFirebaseButton.Click += new System.Windows.RoutedEventHandler(this.TestFirebase_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.AccountSettingsButton = ((System.Windows.Controls.Button)(target));
            
            #line 183 "..\..\..\MainWindow.xaml"
            this.AccountSettingsButton.Click += new System.Windows.RoutedEventHandler(this.OpenSettings_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.ChatsContent = ((System.Windows.Controls.Grid)(target));
            return;
            case 17:
            this.TeamsContent = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 18:
            this.TeamEntryOptionsButton = ((System.Windows.Controls.Button)(target));
            
            #line 223 "..\..\..\MainWindow.xaml"
            this.TeamEntryOptionsButton.Click += new System.Windows.RoutedEventHandler(this.OpenTeamEntryOptions_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.TeamEntryOptionsPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 20:
            
            #line 249 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ShowJoinTeam_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            
            #line 258 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ShowCreateTeam_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.TeamsEmptyStateCard = ((System.Windows.Controls.Border)(target));
            return;
            case 23:
            this.TeamJoinCard = ((System.Windows.Controls.Border)(target));
            return;
            case 24:
            this.TeamJoinCodeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 25:
            
            #line 290 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.JoinTeamByCode_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            
            #line 300 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelTeamEntry_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            this.TeamJoinStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 28:
            this.TeamCreationCard = ((System.Windows.Controls.Border)(target));
            return;
            case 29:
            
            #line 327 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelTeamEntry_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.TeamNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            this.TeamCourseComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 32:
            this.TeamClassComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 33:
            this.TeamClassIdTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 34:
            this.TeamUcInput = ((System.Windows.Controls.ComboBox)(target));
            
            #line 384 "..\..\..\MainWindow.xaml"
            this.TeamUcInput.KeyDown += new System.Windows.Input.KeyEventHandler(this.TeamUcInput_KeyDown);
            
            #line default
            #line hidden
            return;
            case 35:
            
            #line 395 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddTeamUc_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            this.TeamUcsPanel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 37:
            this.TeamMemberInput = ((System.Windows.Controls.ComboBox)(target));
            
            #line 422 "..\..\..\MainWindow.xaml"
            this.TeamMemberInput.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.TeamMemberInput_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 423 "..\..\..\MainWindow.xaml"
            this.TeamMemberInput.KeyDown += new System.Windows.Input.KeyEventHandler(this.TeamMemberInput_KeyDown);
            
            #line default
            #line hidden
            return;
            case 38:
            
            #line 434 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddTeamMember_Click);
            
            #line default
            #line hidden
            return;
            case 39:
            this.TeamMembersPanel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 40:
            this.CreateTeamButton = ((System.Windows.Controls.Button)(target));
            
            #line 452 "..\..\..\MainWindow.xaml"
            this.CreateTeamButton.Click += new System.Windows.RoutedEventHandler(this.CreateTeam_Click);
            
            #line default
            #line hidden
            return;
            case 41:
            this.TeamCreationStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 42:
            this.TeamListCard = ((System.Windows.Controls.Border)(target));
            return;
            case 43:
            this.TeamListPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 44:
            this.TeamWorkspaceCard = ((System.Windows.Controls.Border)(target));
            return;
            case 45:
            this.TeamWorkspaceHost = ((System.Windows.Controls.ContentControl)(target));
            return;
            case 46:
            this.CalendarContent = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 47:
            this.FilesContent = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 48:
            this.SettingsContent = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 49:
            this.AccountNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 50:
            this.NicknameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 51:
            this.ProfessionalTitleTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 52:
            this.ProgrammingLanguageInput = ((System.Windows.Controls.ComboBox)(target));
            
            #line 548 "..\..\..\MainWindow.xaml"
            this.ProgrammingLanguageInput.KeyDown += new System.Windows.Input.KeyEventHandler(this.ProgrammingLanguageInput_KeyDown);
            
            #line default
            #line hidden
            return;
            case 53:
            
            #line 559 "..\..\..\MainWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddProgrammingLanguage_Click);
            
            #line default
            #line hidden
            return;
            case 54:
            this.ProgrammingLanguagesTagsPanel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 55:
            this.BioTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 56:
            this.SkillsTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 57:
            this.PortfolioLinkTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 58:
            this.LinkedInLinkTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 59:
            this.SaveProfessionalProfileButton = ((System.Windows.Controls.Button)(target));
            
            #line 605 "..\..\..\MainWindow.xaml"
            this.SaveProfessionalProfileButton.Click += new System.Windows.RoutedEventHandler(this.SaveProfessionalProfile_Click);
            
            #line default
            #line hidden
            return;
            case 60:
            this.ProfessionalProfileStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 61:
            this.LogoutButton = ((System.Windows.Controls.Button)(target));
            
            #line 631 "..\..\..\MainWindow.xaml"
            this.LogoutButton.Click += new System.Windows.RoutedEventHandler(this.LogoutButton_Click);
            
            #line default
            #line hidden
            return;
            case 62:
            this.ChatDarkModeToggle = ((System.Windows.Controls.CheckBox)(target));
            
            #line 686 "..\..\..\MainWindow.xaml"
            this.ChatDarkModeToggle.Checked += new System.Windows.RoutedEventHandler(this.ChatDarkModeToggle_Changed);
            
            #line default
            #line hidden
            
            #line 687 "..\..\..\MainWindow.xaml"
            this.ChatDarkModeToggle.Unchecked += new System.Windows.RoutedEventHandler(this.ChatDarkModeToggle_Changed);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

